# Generated by Django 5.2 on 2025-04-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lostitem_category_lostitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='category',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Accessories', 'Accessories'), ('Transportation Card', 'Transportation Card'), ('ID Card', 'ID Card'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='founditem',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
